INSERT INTO employees (
    employee_id, 
    first_name, 
    last_name, 
    email, 
    contact_email, 
    phone, 
    department_id, 
    position, 
    employment_type, 
    status, 
    join_date, 
    manager_id, 
    salary, 
    address, 
    emergency_contact_name, 
    emergency_contact_phone, 
    emergency_contact_relationship, 
    created_at, 
    updated_at
) VALUES (
    'WE_IN017', 
    'Sawan', 
    'Kumar', 
    'sawan@wellnessextract.com', 
    'sawan@wellnessextract.com', 
    '+91-9876543210', 
    1, 
    'Software Developer', 
    'Full-time', 
    'Active', 
    '2023-01-15', 
    NULL, 
    75000, 
    '{"street":"123 Tech Street","city":"Mumbai","state":"Maharashtra","country":"India","postal_code":"400001"}', 
    'Emergency Contact', 
    '+91-9876543211', 
    'Spouse', 
    NOW(), 
    NOW()
);
